version: '3.8'

services:
  discovery-service:
    build:
      context: ../discovery-service
      dockerfile: Dockerfile-discovery
    ports:
      - 8761:8761
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
#    command: ./gradlew clean bootRun --args='--spring.profiles.active=dev'
    networks:
      - reserve-network

  reservation-service:
    build:
      context: ../reservation
      dockerfile: Dockerfile-reservation
    ports:
      - 8084:8084
      - 5006:5006
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
   # command: ./gradlew clean bootRun --args='--spring.profiles.active=dev'
    networks:
      - reserve-network

  arena-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
    #command: ./gradlew clean bootRun --args='--spring.profiles.active=dev'
    networks:
      - reserve-network

  mongo-arenas:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reserve-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

networks:
  reserve-network:

volumes:
  mongodb_data: