version: '3.8'

services:
  arena-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
    command: ./gradlew clean bootRun --args='--spring.profiles.active=dev'
#    command: ["java", "-jar", "reserveService.jar"]

    networks:
      - reserve-network

  mongo-arenas:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reserve-network


networks:
  reserve-network:

volumes:
  mongodb_data: