version: '3.8'

services:
  reserve-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
    command: ./gradlew bootRun
#    command: ["java", "-jar", "reserveService.jar"]

    networks:
      - reserve-network

  mongo-reserve:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reserve-network


networks:
  reserve-network:

volumes:
  mongodb_data: