spring:
  application:
    name: reserve-service
  data:
    mongodb:
      user: test
      password: passwordvalue
      uri: mongodb://mongo-mongo-express-1:27017/db

server:
  port: 8083
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic