spring:
  application:
    name: ArenaManagementService
  data:
    mongodb:
      user: root
      password: example
      uri: mongodb://arenamanagementservice-mongo-arenas-1:27017/arena-management
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-consumer-group

server.port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://arenamanagementservice-discovery-service-1:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic