spring:
  application:
    name: ArenaManagementService
  data:
    mongodb:
      user: root
      password: example
      uri: mongodb://ArenaManagementService-mongo-reserve-1:27017/arena-management


server.port: 8083
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic